JEST_CONFIG = """module.exports = {{
    moduleFileExtensions: ['js', 'ts'],
    rootDir: 'src',
    testMatch: ['**/*.spec.ts', '**/*.test.ts'],
    testPathIgnorePatterns: {files_to_ignore},
    transform: {{
      '^.+\\.ts$': 'ts-jest',
    }},
    coveragePathIgnorePatterns: [
      '/node_modules/',
      '/dist/',
      '/decorators/',
    ],
    collectCoverageFrom: ['**/*.(t|j)s'],
    coverageDirectory: '../coverage',
    testEnvironment: 'node',
    coverageReporters: ['text-summary', 'html'],
  }};
"""

JEST_BASE_CONFIG = """module.exports = {
    moduleFileExtensions: ['js', 'ts'],
    rootDir: 'src',
    testMatch: ['**/*.spec.ts', '**/*.test.ts'],
    testPathIgnorePatterns: [
      '\\.d\\.ts$', 
      '/node_modules/', 
      '/dist/', 
      '/tests/',
      '/failed_tests/',
      '/migrations/',
      'main\\.ts$',
      'main\\.js$',
      '\\.config\\.ts$',
      '\\.config\\.js$',
      '\\.module\\.ts$',
      '\\.module\\.js$',
      '\\-config\\.ts$',
      '\\-config\\.js$',
      '\\.entity\\.ts$',
      '\\.entity\\.js$',
      '\\.dto\\.ts$',
      '\\.dto\\.js$',
      '\\.interface\\.ts$',
      '\\.interface\\.js$',
      '\\-swagger\\.ts$',
      '\\-swagger\\.js$',
    ],
    transform: {
      '^.+\\.ts$': 'ts-jest',
    },
    coveragePathIgnorePatterns: [
      '/node_modules/',
      '/dist/',
      '/decorators/',
    ],
    collectCoverageFrom: [
      '**/*.(t|j)s',
      '!**/migrations/**',
      '!**/main.ts',
      '!**/main.js',
      '!**/*.config.ts',
      '!**/*.config.js',
      '!**/*.module.ts',
      '!**/*.module.js',
      '!**/*-config.ts',
      '!**/*-config.js',
      '!**/*.entity.ts',
      '!**/*.entity.js',
      '!**/*.dto.ts',
      '!**/*.dto.js',
      '!**/*.interface.ts',
      '!**/*.interface.js',
      '!**/*-swagger.ts',
      '!**/*-swagger.js',
    ],
    coverageDirectory: '../coverage',
    testEnvironment: 'node',
    coverageReporters: ['text-summary', 'html'],
  };
"""
